{
 "title": "UCS Chassis - Traffic",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   { "name": "polling_interval", "query": "60" },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from \"$db\".\"$rp\".\"FIEnvStats\" with key=domain where $timeFilter"
   },
   {
    "name": "chassis",
    "label": "Chassis",
    "query": "show tag values from \"$db\".\"$rp\".\"BackplanePortStats\" with key=chassis where domain =~ /$domain/ and  $timeFilter"
   },
   {
    "name": "bp_port",
    "label": "Backplane Ports",
    "query": "show tag values from \"$db\".\"$rp\".\"BackplanePortStats\" with key=bp_port where domain =~ /$domain/ and chassis =~ /$chassis/ and  $timeFilter"
   },
   {
    "name": "domain_name",
    "query": "SELECT \"name\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE \"domain\" =~ /^$domain$/  and $timeFilter"
   },
   {
    "name": "domain_location",
    "query": "select location from (select location,last(load) from \"$db\".\"$rp\".\"FIEnvStats\" where (\"domain\" =~ /^$domain$/)) where  $timeFilter"
   },
   {
    "name": "utm_collector_ver",
    "query": "select last(utm_collector_ver) from \"$db\".\"$rp\".\"FIEnvStats\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "![Cisco UCS Architecture](/public/img/utm/ucs_architecture.png)\nUTM collector - v$utm_collector_ver  \nUTM GUI - v0.52  \nby Paresh Gupta",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/cisco_logo.png' width=\"120\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>UTM - UCS Traffic Monitoring</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/your_logo.png' alt=\"\" width=\"120\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "\n<h2 style=\"text-align: center;\"><span style=\"color: #6666FF;\"><strong>UCS Chassis Traffic - <span style=\"color: #ff00ff;\"> $chassis</span> in <span style=\"color: #ff00ff;\"> $domain</span></span></strong></h2>\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic Per Server - Ingress Eth - $chassis in $domain",
   "type": "graph",
   "description": "**Use Case**: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n![Chassis Traffic](/public/img/utm/chassis_traffic.png)\n\n**How to use**: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(RX)*8 as \"RX\" from (SELECT max((\"bytes_rx_delta\")) /[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time([[__interval_ms]]ms),vif_name,service_profile) where $timeFilter GROUP BY time([[__interval_ms]]ms),service_profile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Per Server - Egress Eth - $chassis in $domain",
   "type": "graph",
   "description": "**Use Case**: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n![Chassis Traffic](/public/img/utm/chassis_traffic.png)\n\n**How to use**: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(TX)*8 as \"TX\" from (SELECT max((\"bytes_tx_delta\")) /[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'Eth') AND $timeFilter GROUP BY time([[__interval_ms]]ms),vif_name,service_profile) where $timeFilter GROUP BY time([[__interval_ms]]ms),service_profile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Per Server - Ingress FC - $chassis in $domain",
   "type": "graph",
   "description": "**Use Case**: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n![Chassis Traffic](/public/img/utm/chassis_traffic.png)\n\n**How to use**: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(RX)*8 as \"RX\" from (SELECT max((\"bytes_rx_delta\")) /[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time([[__interval_ms]]ms),vif_name,service_profile) where $timeFilter GROUP BY time([[__interval_ms]]ms),service_profile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Per Server - Egress FC - $chassis in $domain",
   "type": "graph",
   "description": "**Use Case**: Most and least busy service profiles, AKA top-talker and bottom-talker blades\n\n![Chassis Traffic](/public/img/utm/chassis_traffic.png)\n\n\n**How to use**: Monitor the traffic pattern over time in the graph. Sort by clicking on the avg or current.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_service_profile",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(TX)*8 as \"TX\" from (SELECT max((\"bytes_tx_delta\")) /[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"transport\" = 'FC') AND $timeFilter GROUP BY time([[__interval_ms]]ms),vif_name,service_profile) where $timeFilter GROUP BY time([[__interval_ms]]ms),service_profile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[  IOM Fabric Port <--> FI Server Port  ] Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-A Server Ports",
     "type": "table",
     "description": "**Use Case**: Find links between Fabric Interconnect server ports and fabric ports on IOM in a UCS Chassis\n\n![FI Server Ports to IOM and FEX](/public/img/utm/fi_server_port_to_iom_fabric_port.png)\n\n**How to use**: The table is a quick-reference which can further be used at other places for detailed troubleshooting.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(oper_state) as \"Operational State\", channel as \"Port-Chanel\",peer as \"Peer\", peer_port as \"Peer Port\", peer_type as \"Peer Type\", oper_speed as \"Speed (Gbps)\"  FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/) AND fi_id = 'A' AND channel != '' AND $timeFilter GROUP BY port ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-B Server Ports",
     "type": "table",
     "description": "**Use Case**: Find links between Fabric Interconnect server ports and fabric ports on IOM in a UCS Chassis\n\n![FI Server Ports to IOM and FEX](/public/img/utm/fi_server_port_to_iom_fabric_port.png)\n\n**How to use**: The table is a quick-reference which can further be used at other places for detailed troubleshooting.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(oper_state) as \"Operational State\", channel as \"Port-Chanel\",peer as \"Peer\", peer_port as \"Peer Port\", peer_type as \"Peer Type\", oper_speed as \"Speed (Gbps)\"  FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/) AND fi_id = 'B' AND channel != '' AND $timeFilter GROUP BY port ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "[  IOM/FEX Backplane Port <--> Server Adaptor Port ] Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports in [[chassis]] (connected via FI-A)",
     "type": "table",
     "description": "**Use Case**: Find links between IOM/FEX backplane ports and server\n\n![Backplane Ports to Adaptor Ports](/public/img/utm/backplane_ports_to_adaptor_ports.png)\n\n**How to use**: The table is a quick-reference which can further be used at other places for detailed troubleshooting.\n\n**Details**: A blade or rack server can have multiple adaptors. Each adaptor may have multiple ports. Each adaptor port has one-to-one connectivity to IOM/FEX backplane port. These connections may or may not be aggregated under a port-channel.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT bp_port as \"Backplane port\",last(oper_state) as \"Operational State\", channel as \"Port-Channel\", speed as \"Speed\", peer as \"Peer\", peer_port as \"Peer Port\", peer_type as \"Peer Type\", peer_service_profile as \"Peer Service Profile\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"chassis\" =~ /^$chassis$/) AND fi_id = 'A' AND channel != '' AND $timeFilter GROUP BY bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports in [[chassis]] (connected via FI-B)",
     "type": "table",
     "description": "**Use Case**: Find links between IOM/FEX backplane ports and server\n\n![Backplane Ports to Adaptor Ports](/public/img/utm/backplane_ports_to_adaptor_ports.png)\n\n**How to use**: The table is a quick-reference which can further be used at other places for detailed troubleshooting.\n\n**Details**: A blade or rack server can have multiple adaptors. Each adaptor may have multiple ports. Each adaptor port has one-to-one connectivity to IOM/FEX backplane port. These connections may or may not be aggregated under a port-channel.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT bp_port as \"Backplane port\",last(oper_state) as \"Operational State\", channel as \"Port-Channel\", speed as \"Speed\", peer as \"Peer\", peer_port as \"Peer Port\", peer_type as \"Peer Type\", peer_service_profile as \"Peer Service Profile\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/) AND (\"chassis\" =~ /^$chassis$/) AND fi_id = 'B' AND channel != '' AND $timeFilter GROUP BY bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Backplane Port $bp_port Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "bp_port",
   "collapsed": true,
   "panels": [
    {
     "title": "Backplane Port Utilization - TX - $bp_port ",
     "type": "graph",
     "description": "**Use Case**: Monitor the utilization of IOM backplane ports\n\n![Backplane port utilization](/public/img/utm/chassis_backplane_port_utilization.png)\n\n**How to use**: Start by selecting a UCS domain and chassis. Then, select *Backplane port(s)*. The graphs for RX and TX traffic are auto-generated side-by-side. To use the output:\n  - Look at Left Y-axis for utilization in (Giga or Mega) bits per second and Right Y-axis for utilization in %.\n  - *Util Max* shows max speed of the link. *% Max* always shows 100%.\n  - TX traffic on backplane ports is inbound to the blade server. Similarly, RX traffic on backplane ports is outbound from the blade server.\n\nYou can select more than one values or All from *Backplane Ports*. The RX and TX graphs are auto-generated for the selected values. You may want to look at everything when you don't know where to start or if you are just doing routine monitoring. But it is better to focus on one link at a time and not get overwhelmed by too much information at the same time.\n\n**Details**: An IOM backplane port has one-to-one connectivity to a single adaptor port on a server. Multiple vNIC/vHBA may be using this link. To find the traffic distribution per vNIC/vHBA, go to the service profile monitoring.\n- The options under *Uplink Port Channel* drop-down are automatically updated based on the selected UCS domain and Chassis",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"bytes_tx_delta\") *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port,peer_service_profile",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"speed\") *1000000000 AS \"TX MAX\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"bytes_tx_delta\") *8/[[polling_interval]]/max(\"speed\")/1000000000 AS \"TX %\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane Port Utilization - RX - $bp_port",
     "type": "graph",
     "description": "**Use Case**: Monitor the utilization of IOM backplane ports\n\n![Backplane port utilization](/public/img/utm/chassis_backplane_port_utilization.png)\n\n**How to use**: Start by selecting a UCS domain and chassis. Then, select a *Backplane port(s)*. The graphs for RX and TX traffic are auto-generated side-by-side. To use the output:\n  - Look at Left Y-axis for utilization in (Giga or Mega) bits per second and Right Y-axis for utilization in %.\n  - *Util Max* shows max speed of the link. *% Max* always shows 100%.\n  - TX traffic on backplane ports is inbound to the blade server. Similarly, RX traffic on backplane ports is outbound from the blade server.\n\nYou can select more than one values or All from *Backplane Ports*. The RX and TX graphs are auto-generated for the selected values. You may want to look at everything when you don't know where to start or if you are just doing routine monitoring. But it is better to focus on one link at a time and not get overwhelmed by too much information at the same time.\n\n**Details**: An IOM backplane port has one-to-one connectivity to a single adaptor port on a server. Multiple vNIC/vHBA may be using this link. To find the traffic distribution per vNIC/vHBA, go to the service profile monitoring.\n- The options under *Uplink Port Channel* drop-down are automatically updated based on the selected UCS domain and Chassis",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"bytes_rx_delta\") *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port,peer_service_profile",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"speed\") *1000000000 AS \"RX MAX\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"bytes_rx_delta\") *8/[[polling_interval]]/max(\"speed\")/1000000000 AS \"RX %\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval),bp_port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}