{
 "title": "Congestion Monitoring",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "location",
    "label": "Location",
    "query": "show tag values from \"$db\".\"$rp\".\"Servers\" with key=location where $timeFilter"
   },
   {
    "name": "domain",
    "label": "UCS Domain",
    "query": "show tag values from \"$db\".\"$rp\".\"FIEnvStats\" with key=domain where location =~ /$location/ and $timeFilter"
   },
   { "name": "fi_id", "label": "FI ID", "query": "A,B" },
   {
    "name": "uplink",
    "label": "Uplink Port",
    "query": "show tag values from \"$db\".\"$rp\".\"VnicStats\" with key=pinned_uplink where domain =~ /$domain/ and fi_id =~ /$fi_id/ and  $timeFilter"
   },
   {
    "name": "server_port",
    "label": "Server Port",
    "query": "show tag values from \"$db\".\"$rp\".\"FIServerPortStats\" with key=port where domain =~ /$domain/ and fi_id =~ /$fi_id/ and channel != '' and $timeFilter"
   },
   {
    "name": "chassis",
    "label": "Chassis",
    "query": "show tag values from \"$db\".\"$rp\".\"FIServerPortStats\" with key=peer where domain =~ /$domain/ and fi_id =~ /$fi_id/ and port =~ /$server_port/ and  $timeFilter"
   },
   {
    "name": "bp_port",
    "label": "Backplane Port",
    "query": "show tag values from \"$db\".\"$rp\".\"VnicStats\" with key=peer_port where domain =~ /$domain/ and fi_id =~ /$fi_id/ and pinned_uplink =~ /$uplink/ and chassis =~ /$chassis/ and  $timeFilter"
   },
   { "name": "polling_interval", "query": "60" },
   {
    "name": "utm_collector_ver",
    "query": "select last(utm_collector_ver) from \"$db\".\"$rp\".\"FIEnvStats\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "![Cisco UCS Architecture](/public/img/utm/ucs_architecture.png)\nUTM collector - v$utm_collector_ver  \nUTM GUI - v0.52  \nby Paresh Gupta",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/cisco_logo.png' width=\"120\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>UTM - UCS Traffic Monitoring</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/your_logo.png' alt=\"\" width=\"120\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "description": "Find the root-cause of the Ingress Traffic Congestion observed on FI Uplink ports",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "\n<h2 style=\"text-align: center;\"><span style=\"color: #0085FC;\"><strong>Congestion Monitoring - </span><span style=\"color: #ff00ff;\">$domain</span></strong></h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "options": {
    "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ff00;color: black\">Ingress</span> traffic</h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ffff;color: black\">Egress</span> traffic</h2>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 FI Server Ports - Congestion Against Ingress Traffic - $domain",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"PAUSE against Ingress Traffic\",location,domain,fi_id,port,peer,10) as \"PAUSE Sent to FI Server Ports\" from (select sum(\"PAUSE against Ingress Traffic\") as \"PAUSE against Ingress Traffic\" from (SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"PAUSE against Ingress Traffic\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($__interval),location,domain,fi_id,port,peer) where $timeFilter GROUP BY location,domain,fi_id,port,peer) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 FI Server Ports - Congestion Against Egress Traffic - $domain",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"PAUSE against Egress Traffic\",location,domain,fi_id,port,peer,10) as \"PAUSE Sent by FI Server Ports\" from (select sum(\"PAUSE against Egress Traffic\") as \"PAUSE against Egress Traffic\" from (SELECT non_negative_difference(max(\"pause_tx\"))/elapsed(max(\"pause_tx\"),1s) AS \"PAUSE against Egress Traffic\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ AND $timeFilter GROUP BY time($__interval),location,domain,fi_id,port,peer) where $timeFilter GROUP BY location,domain,fi_id,port,peer) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Servers - Congestion Against Ingress Traffic - $domain",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"PAUSE against Ingress Traffic\",location,domain,chassis,peer_service_profile,10) as \"PAUSE Sent by Servers\" from (select sum(\"PAUSE against Ingress Traffic\") as \"PAUSE against Ingress Traffic\" from (SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"PAUSE against Ingress Traffic\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE \"domain\" =~ /^$domain$/ and $timeFilter GROUP BY time($__interval),location,domain,chassis,fi_id,bp_port,peer_service_profile) where $timeFilter and peer_service_profile != 'Unknown' GROUP BY chassis,peer_service_profile,location,domain)  where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Servers - Congestion Against Egress Traffic - $domain",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(\"PAUSE against Egress Traffic\",chassis,peer_service_profile,location,domain,10) as \"PAUSE Sent by Servers\" from (select sum(\"PAUSE against Egress Traffic\") as \"PAUSE against Egress Traffic\" from (SELECT non_negative_difference(max(\"pause_tx\"))/elapsed(max(\"pause_tx\"),1s) AS \"PAUSE against Egress Traffic\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE \"domain\" =~ /^$domain$/ and $timeFilter GROUP BY time($__interval),chassis,fi_id,bp_port,peer_service_profile,location,domain) where $timeFilter and peer_service_profile != 'Unknown' GROUP BY chassis,peer_service_profile,location,domain)  where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAUSE Monitoring on FI Server Ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 9 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ff00;color: black\">Ingress</span> traffic</h2>"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 9 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ffff;color: black\">Egress</span> traffic</h2>"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-A Server port - RX PAUSE Monitoring",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FI Server Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/fi_server_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display RX PAUSE received on the FI Server Ports. These PAUSE frames are sent by the connected devices (FEX, IOM or Servers) when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_port from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "peer_chassis" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIServerPortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A' AND \"port\" =~ /^$server_port$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
       ]
      }
     ]
    },
    {
     "title": "FI-A Server port - TX PAUSE Monitoring",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FI Server Ports. \n\n![Server Ports TX PAUSE](/public/img/utm/fi_server_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display TX PAUSE sent by the FI Server Ports. These PAUSE frames are sent to the connected devices (FEX, IOM or Servers) when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_port to $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "peer_chassis" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIServerPortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A' AND \"port\" =~ /^$server_port$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
       ]
      }
     ]
    },
    {
     "title": "FI-B Server port - RX PAUSE Monitoring",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FI Server Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/fi_server_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display RX PAUSE received on the FI Server Ports. These PAUSE frames are sent by the connected devices (FEX, IOM or Servers) when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_port from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "peer_chassis" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIServerPortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B' AND \"port\" =~ /^$server_port$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\"",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
       ]
      }
     ]
    },
    {
     "title": "FI-B Server port - TX PAUSE Monitoring",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FI Server Ports. \n\n![Server Ports TX PAUSE](/public/img/utm/fi_server_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and FI Server Port (s). The graphs display TX PAUSE sent by the FI Server Ports. These PAUSE frames are sent to the connected devices (FEX, IOM or Servers) when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for FI Server Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect FI Server port with unusual PAUSE frame activity, the next step depends on the type of connected device.\n-\tIf the connected device is a server, you have found the ultimate traffic destination or Congestion source.\n-\tIf the connected device is a FEX or IOM in a chassis, monitor the congestion on the backplane ports to find the (blade) server (s).\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col on $tag_port to $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "peer_chassis" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIServerPortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B' AND \"port\" =~ /^$server_port$/) AND $timeFilter GROUP BY time($__interval), \"port\", \"peer\" fill(linear)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$server_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PAUSE Monitoring on Backplane Ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ff00;color: black\">Ingress</span> traffic</h2>"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
     "options": {
      "content": "<h2 style=\"text-align: center;\">Congestion against <span style=\"background-color: #00ffff;color: black\">Egress</span> traffic</h2>"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports - RX PAUSE in Chassis $chassis via FI-A",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display RX PAUSE received on the FEX/IOM Backplane Ports. These PAUSE frames are sent by the connected servers when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bp_port in $tag_chassis from $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A' AND \"chassis\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports - TX PAUSE in Chassis $chassis via FI-A",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display TX PAUSE sent by the FEX/IOM Backplane Ports. These PAUSE frames are sent to the connected servers when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bp_port in $tag_chassis to $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A' AND \"chassis\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "A" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports - RX PAUSE in Chassis $chassis via FI-B",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against ingress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_rx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display RX PAUSE received on the FEX/IOM Backplane Ports. These PAUSE frames are sent by the connected servers when they must apply backpressure on the incoming traffic. *Note*: Server Ingress traffic is TX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server sends PAUSE frames if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bp_port in $tag_chassis from $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  /elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B' AND \"chassis\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    },
    {
     "title": "Backplane Ports - TX PAUSE in Chassis $chassis via FI-B",
     "type": "graph",
     "description": "**Use Case**: Monitor congestion against egress traffic on FEX/IOM Backplane Ports. \n\n![Server Ports RX PAUSE](/public/img/utm/backplane_port_tx_pause.png)\n\n**How to use**:  Select a UCS domain and Chassis. The graphs display TX PAUSE sent by the FEX/IOM Backplane Ports. These PAUSE frames are sent to the connected servers when the backpressure must be applied against the outgoing traffic. *Note*: Server Egress traffic is RX for Backplane Ports.\n\nPAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are used for FC traffic only (no-drop class). Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_bp_port in $tag_chassis to $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "peer_service_profile" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B' AND \"chassis\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"chassis\", \"bp_port\", \"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=", "value": "B" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress Traffic Congestion in Chassis - $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "title": "RX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of ingress traffic congestion. \n\n![](/public/img/utm/chassis_ingress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to receive traffic at the incoming rate. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with RX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied by Server against ingress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server sends PAUSE frames to IOM/FEX backplane port if it is unable to receive the traffic at the ingress rate. These frames are reported as RX PAUSE on IOM/FEX backplane ports. \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col <-- $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))  / elapsed(max(pause_rx),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\" fill(null)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "RX Traffic to vIFs from Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_rx_delta\")  *8/[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Egress Traffic Congestion in Chassis - $chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "chassis",
   "collapsed": true,
   "panels": [
    {
     "title": "TX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\"",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "repeat": "bp_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\"",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\"",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\"",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX PAUSE on Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "**Use Case**: Find the root cause of egress traffic congestion. \n\n![](/public/img/utm/chassis_egress_congestion.png)\n\n**How to use**:  Select a UCS domain, chassis, and Backplane Port. One row is created per chassis. Graphs are generated for backplanes ports in that chassis within the row. Choose one Chassis at a time if you have many chassis. \n\nFI and FEX/IOM ports do not originate or terminate the traffic. Mostly, the real cause of congestion is one of the servers which is unable to sending data faster than the receiver can ingest it. Try to find one of those servers by comparing unusual PAUSE frame activity and traffic spikes. Refer to the graphs on the left with TX PAUSE frames on IOM/FEX backplane ports which indicate a backpressure applied to Servers against egress traffic.  PAUSE frames may be exchanged under normal conditions also. So, find unusual PAUSE frame activity with below symptoms (not an exhaustive list):\n- PAUSE frame rate in tens or hundreds per second is bad. Thousands, tens-of-thousands, or Millions per second is terribly bad.\n- Look for spike in PAUSE frame rate. Low stable values are probably fine.\n- Does one port among many other similar ports has higher PAUSE frame activity?\n\nOnce you have a suspect backplane port with unusual PAUSE frame activity, look at the graph on the right which shows the service profile and vNIC/vHBA traffic using that backplane port. High traffic rate or traffic spikes, especially with matching timestamp with unusual PAUSE frame activity, indicate that high utilization is the cause of congestion.\n\n**Details**: \n- A server receives PAUSE frames if it is transmitting data faster than the receiver can accept it. These frames are reported as TX PAUSE on the connected port (on FI or FEX or IOM). \n- PAUSE frames are not reported at per vNIC/vHBA granularity. \n- PAUSE frames are used by FC traffic (no-drop class) only. Congestion in Eth traffic is generally indicated by frame drops.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col --> $tag_peer_service_profile",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "chassis" ], "type": "tag" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_tx\"))  / elapsed(max(pause_tx),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"BackplanePortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"bp_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"chassis\", \"bp_port\",\"peer_service_profile\"",
       "select": [
        [
         { "params": [ "pause_tx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "TX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "TX Traffic from vIFs to Backplane Port $bp_port in $chassis",
     "type": "graph",
     "description": "Refer to the description of the panel on the left. Compare high PAUSE frame activity from the left graph to the high traffic activity in this graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_profile $tag_vif_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "service_profile" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  *8/[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"VnicStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"chassis\" =~ /^$chassis$/ AND \"peer_port\" =~ /^$bp_port$/) AND $timeFilter GROUP BY time($__interval), \"vif_name\", \"service_profile\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *8/[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "chassis", "operator": "=~", "value": "/^$chassis$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FI Server Port - Ingress Traffic Congestion and Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-A Server Ports ",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"bytes_tx_delta\") *8/ [[polling_interval]])/(max(oper_speed)*1000000000) as \"Peak % TX\", max(\"bytes_tx_delta\") *8/ [[polling_interval]] as \"Peak TX\",max(oper_speed) as \"Speed\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ and \"channel\" != '' and fi_id='A') AND $timeFilter GROUP BY port,peer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"RX PAUSE\") as \"RX PAUSE\" from (SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and fi_id='A' and \"channel\" != '' AND $timeFilter GROUP BY time($__interval),port) where $timeFilter GROUP BY port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-B Server Ports",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"bytes_tx_delta\") *8/ [[polling_interval]])/(max(oper_speed)*1000000000)*100 as \"Peak % TX\", max(\"bytes_tx_delta\") *8/ [[polling_interval]] as \"Peak TX\",max(oper_speed) as \"Speed\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ and \"channel\" != '' and fi_id='B') AND $timeFilter GROUP BY port,peer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"RX PAUSE\") as \"RX PAUSE\" from (SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and fi_id='B' and \"channel\" != '' AND $timeFilter GROUP BY time($__interval),port) where $timeFilter GROUP BY port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-A Server Port - TX Traffic vs RX PAUSE - $server_port ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "repeat": "server_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  / [[polling_interval]]*8 AS \"TX\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='A') AND $timeFilter GROUP BY time($__interval), \"port\",peer fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / [[polling_interval]]*8" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" },
        { "condition": "AND", "key": "vif_name", "operator": "=~", "value": "/^$vif$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT last(\"oper_speed\")  *1000000000 AS \"TX Util Max\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='A') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *1000000000" ], "type": "math" },
         { "params": [ "TX Util Max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and \"port\" =~ /^$server_port$/ and fi_id='A' AND $timeFilter GROUP BY time($__interval),domain,fi_id,port fill(linear)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "FI-B Server Port - TX Traffic vs RX PAUSE - $server_port ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "repeat": "server_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT max(\"bytes_tx_delta\")  / [[polling_interval]]*8 AS \"TX\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='B') AND $timeFilter GROUP BY time($__interval), \"port\",peer fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / [[polling_interval]]*8" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" },
        { "condition": "AND", "key": "vif_name", "operator": "=~", "value": "/^$vif$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT last(\"oper_speed\")  *1000000000 AS \"TX Util Max\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='B') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *1000000000" ], "type": "math" },
         { "params": [ "TX Util Max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(max(\"pause_rx\"))/elapsed(max(\"pause_rx\"),1s) AS \"RX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and \"port\" =~ /^$server_port$/ and fi_id='B' AND $timeFilter GROUP BY time($__interval),domain,fi_id,port fill(linear)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FI Server Port - Egress Traffic Congestion and Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'A') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "agenty-flowcharting-panel",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 14 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"leadership\") as \"leadership\" FROM \"$db\".\"$rp\".\"FIEnvStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" = 'B') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Server ports FI-A",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"bytes_rx_delta\") *8/ [[polling_interval]])/(max(oper_speed)*1000000000)*100 as \"Peak % RX\", max(\"bytes_rx_delta\") *8/ [[polling_interval]] as \"Peak RX\", max(oper_speed) as \"Speed\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ and \"channel\" != '' and fi_id='A') AND $timeFilter GROUP BY port,peer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"TX PAUSE\") as \"TX PAUSE\" from (SELECT non_negative_difference(max(\"pause_tx\"))/elapsed(max(\"pause_tx\"),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and fi_id='A' and \"channel\" != '' AND $timeFilter GROUP BY time($__interval),port) where $timeFilter GROUP BY port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Server ports FI-B",
     "type": "table",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"bytes_rx_delta\") *8/ [[polling_interval]])/(max(oper_speed)*1000000000)*100 as \"Peak % RX\", max(\"bytes_rx_delta\") *8/ [[polling_interval]] as \"Peak RX\", max(oper_speed) as \"Speed\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"domain\" =~ /^$domain$/ and \"channel\" != '' and fi_id='B') AND $timeFilter GROUP BY port,peer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(\"TX PAUSE\") as \"TX PAUSE\" from (SELECT non_negative_difference(max(\"pause_tx\"))/elapsed(max(\"pause_tx\"),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and fi_id='B' and \"channel\" != '' AND $timeFilter GROUP BY time($__interval),port) where $timeFilter GROUP BY port",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FI-A Server Port - RX Traffic vs TX PAUSE - $server_port ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "repeat": "server_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT mean(\"bytes_rx_delta\")  / [[polling_interval]]*8 AS \"RX\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='A') AND $timeFilter GROUP BY time($__interval), \"port\",peer fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / [[polling_interval]]*8" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" },
        { "condition": "AND", "key": "vif_name", "operator": "=~", "value": "/^$vif$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT last(\"oper_speed\")  *1000000000 AS \"RX Util Max\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='A') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *1000000000" ], "type": "math" },
         { "params": [ "TX Util Max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))/elapsed(mean(\"pause_tx\"),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and \"port\" =~ /^$server_port$/ and fi_id='A' AND $timeFilter GROUP BY time($__interval),domain,fi_id,port fill(linear)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    },
    {
     "title": "FI-B Server Port - RX Traffic vs TX PAUSE - $server_port",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "repeat": "server_port",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col from $tag_peer",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "vif_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "VnicStats",
       "query": "SELECT mean(\"bytes_rx_delta\")  / [[polling_interval]]*8 AS \"RX\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='B') AND $timeFilter GROUP BY time($__interval), \"port\",peer fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / [[polling_interval]]*8" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "peer_port", "operator": "=~", "value": "/^$bp_port$/" },
        { "condition": "AND", "key": "vif_name", "operator": "=~", "value": "/^$vif$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT last(\"oper_speed\")  *1000000000 AS \"RX Util Max\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE (\"port\" =~ /^$server_port$/ and fi_id='B') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *1000000000" ], "type": "math" },
         { "params": [ "TX Util Max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      },
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "bp_port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "BackplanePortStats",
       "query": "SELECT non_negative_difference(mean(\"pause_tx\"))/elapsed(mean(\"pause_tx\"),1s) AS \"TX PAUSE\" FROM \"$db\".\"$rp\".\"FIServerPortStats\" WHERE \"domain\" =~ /^$domain$/ and \"port\" =~ /^$server_port$/ and fi_id='B' AND $timeFilter GROUP BY time($__interval),domain,fi_id,port fill(linear)",
       "select": [
        [
         { "params": [ "pause_rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ " / [[polling_interval]]" ], "type": "math" },
         { "params": [ "RX PAUSE" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "peer_service_profile", "operator": "=~", "value": "/^$service_profile$/" },
        { "condition": "AND", "key": "bp_port", "operator": "=~", "value": "/^$bp_port$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Reference",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "$domain - FI-$fi_id - Uplink  - RX Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT max(\"bytes_rx_delta\") *8 /[[polling_interval]] AS \"RX\" FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"channel\" != '' and oper_state = 'up') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_rx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*8 /[[polling_interval]]" ], "type": "math" },
         { "params": [ "RX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$uplink$/" }
       ]
      }
     ]
    },
    {
     "title": "$domain - FI-$fi_id - Uplink  - TX Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_port $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "port" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "FIUplinkPortStats",
       "query": "SELECT max(\"bytes_tx_delta\") *8 /[[polling_interval]] AS \"TX\" FROM \"$db\".\"$rp\".\"FIUplinkPortStats\" WHERE (\"domain\" =~ /^$domain$/ AND \"fi_id\" =~ /^$fi_id$/ AND \"channel\" != '' and oper_state = 'up') AND $timeFilter GROUP BY time($__interval), \"port\" fill(linear)",
       "select": [
        [
         { "params": [ "bytes_tx_delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*8 /[[polling_interval]]" ], "type": "math" },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "domain", "operator": "=~", "value": "/^$domain$/" },
        { "condition": "AND", "key": "fi_id", "operator": "=~", "value": "/^$fi_id$/" },
        { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$uplink$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}