{
 "title": "Welcome",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "num_domain",
    "query": "select count(domain) from (SELECT last(\"model\") FROM \"autogen\".\"FIEnvStats\" WHERE $timeFilter GROUP BY domain)"
   },
   {
    "name": "num_chassis",
    "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (chassis!='') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)"
   },
   {
    "name": "num_servers",
    "query": "select count(id) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE $timeFilter GROUP BY domain,chassis,blade,id)"
   },
   {
    "name": "num_locations",
    "query": " SHOW TAG VALUES CARDINALITY FROM \"autogen\".\"FIEnvStats\" WITH KEY=location"
   },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<table style=\"margin-left: auto; margin-right: auto;\" border=\"0\" width=\"100%\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 15%;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/your_logo.png' width=\"300\" /></td>\r\n<td style=\"width: 70%;\">\r\n<h1 style=\"text-align: center;\"><span style=\"color: #299c46;\"><strong>Welcome to UCS Traffic Monitoring at Cisco Systems</strong></span></h1>\r\n<h3 style=\"text-align: center;\"><span style=\"color: #FFFFFF;\">Monitoring <span style=\"color: #B877D9;\">$num_domain</span> UCS domains containing <span style=\"color: #B877D9;\">$num_chassis</span> chassis with </span><span style=\"color: #B877D9;\">$num_servers</span>  servers across <span style=\"color: #B877D9;\">$num_locations</span> locations</span></h3>\r\n</td>\r\n<td style=\"width: 15%;\" valign=\"top\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/utm/cisco_logo.png' alt=\"\" width=\"150\" /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"text-align: left;\"></p>"
  },
  {
   "title": "Alert list",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "US_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Servers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'US') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "China_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Servers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'China') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Italy_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Servers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'Italy') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "UK_blades",
     "groupBy": [
      { "params": [ "[[polling_interval]]s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "Servers",
     "query": "select count(service_profile) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'UK') AND $timeFilter GROUP BY service_profile,domain,chassis,blade)",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "UK" }
     ]
    },
    {
     "alias": "US_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'US') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UK_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'UK') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Italy_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'Italy') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "China_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(count) from (select count(distinct(chassis)) from (SELECT last(\"model\") FROM \"autogen\".\"Servers\" WHERE (\"location\" = 'China') AND $timeFilter GROUP BY service_profile,domain,chassis,blade) group by domain)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location specific monitoring",
   "type": "table",
   "description": "Monitor UCS domains at a specific location by clicking any of the links below",
   "gridPos": { "h": 13, "w": 3, "x": 8, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "show tag values from FIEnvStats with key=location where $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UCS Domain overview",
   "type": "table",
   "description": "Get an overview (inventory, status, etc.) of a specific UCS domain by clicking any of the links below",
   "gridPos": { "h": 13, "w": 3, "x": 11, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "show tag values from FIEnvStats with key=domain where $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Domain traffic monitoring",
   "type": "table",
   "description": "Monitor traffic on a specific UCS domain by clicking any of the links below",
   "gridPos": { "h": 13, "w": 3, "x": 14, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "show tag values from FIEnvStats with key=domain where $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis traffic monitoring",
   "type": "table",
   "description": "Monitor traffic on a chassis in a UCS domain by clicking any of the links below",
   "gridPos": { "h": 13, "w": 3, "x": 17, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "show tag values from FIEnvStats with key=domain where $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service profile traffic monitoring",
   "type": "table",
   "description": "Monitor a specific Service Profile (server) by clicking any of the links below. You can click on any link and search for a specific service profile later.\n\n*Note*: Servers only with a valid service profile are displayed here. For a complete inventory, go to the specific domain page.",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT model FROM \"autogen\".\"Servers\" WHERE service_profile != 'Unknown' and $timeFilter GROUP BY \"service_profile\",domain order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Congestion monitoring - if you know where to start from, like an uplink port on FI",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "content": "<h3 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><a id='this_system' href=\"\" target=\"_blank\">Click here</a></span></h3>\n<script>\n  document.getElementById('this_system').setAttribute('href', 'http://' + window.location.hostname + \":3000/d/Sve32sDZk/fi-uplink-port-ingress-congestion-monitoring\");\n</script>",
   "targets": [
    {
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Congestion monitoring - If you don't know where to start but still have congestion",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "content": "<h3 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><a id='this_system_1' href=\"\" target=\"_blank\">Click here</a></span></h3>\n<script>\n  document.getElementById('this_system_1').setAttribute('href', 'http://' + window.location.hostname + \":3000/d/SVO-VNiWk/chassis-pause-frame-monitoring\");\n</script>",
   "targets": [
    {
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Local system health",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "content": "<h3 style=\"text-align: center;\"><span style=\"color: #ffffff;\"><a id='this_system_3' href=\"\" target=\"_blank\">Local system health</a></span></h3>\n<script>\n  document.getElementById('this_system_3').setAttribute('href', 'http://' + window.location.hostname + \":3000/d/9CXO3jTWz/local-system-health\");\n</script>",
   "targets": [
    {
     "measurement": "FIEnvStats",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$domain$/" }
     ]
    }
   ]
  }
 ]
}